print(''' we have to know what is Boolean types in bases of some datypes indicators ''')
print("what Boolean of zero indicates in Boolean type ?")
print("bool(0): ",bool(0))
print('''what boolean of one indicates in Boolean type ?:''')
print("bool(1): ",bool(1))
print("what empty string indicates in boolean type note :it should not have any spaces between two single qoutes")
print("bool(''): ",bool(''))