s=input("enter the string : ")
print("the upper function makes the whole case uppercase")
print("uppercase : ",s.upper())
print("the lower function makes the whole case lowercase")
print("lowercase : ",s.lower())
